apiVersion: v1
kind: Service
metadata:
  name: core-frontend-service
  labels:
    app: core-frontend
    environment: dev
spec:
  trafficDistribution: PreferSameZone
  selector:
    app: core-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP