apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scf-workflow
  namespace: argo-cd
spec:
  project: scf-workflow
  source:
    repoURL: 'https://github.com/jai-kisan/scf-infrastructure'
    targetRevision: master
    path: lsp/dev/apps/backend/scf-workflow
    directory:
      recurse: true   
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: scf-workflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true